### PR TITLE
Refactor: Timezone Handling to Use ZoneInfo and Replace Deprecated datetime.datetime.utc()

### PR DESCRIPTION
**Pull request by abdullai-t**
####  Summary / Highlights
This pull request addresses two deprecations issues in Django 4:

 - The `pytz` package for timezone handling is deprecated in Django 4 and all occurrences of `pytz` have been refactored to use `zoneinfo.ZoneInfo`.

- The `datetime.datetime.utcnow()` function is deprecated and all occurrences of `datetime.datetime.utcnow()` have been replaced with the recommended `datetime.now(timezone.utc)` to ensure timezone-aware datetime objects in UTC.

#### Requirements (place an `x` in each `[ ]`)
* [x] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [x] I've given my PR a meaningful title.
* [x] I linked this PR to the relevant issue.
* [ ] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [ ] I moved the linked issue to "QA Verification" now that it is ready to merge.

### CODE REVIEW

**Review by Opoku-Agyemang — CHANGES_REQUESTED** [review]
I am still seeing 
```
/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning: DateTimeField FeatureFlag.expires_on received a naive datetime (2024-07-09 14:08:41.596345) while time zone support is active.

```
when we run `make test`

**Comment by abdullai-t** [comment]
> I am still seeing
> 
> ```
> /opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning: DateTimeField FeatureFlag.expires_on received a naive datetime (2024-07-09 14:08:41.596345) while time zone support is active.
> ```
> 
> when we run `make test`

All resolved now

**Review by Opoku-Agyemang — APPROVED** [review]
nice work!

**Comment by Opoku-Agyemang** [comment]
The pytz package for timezone handling is deprecated in Django 4 and all occurrences of pytz have been refactored to use zoneinfo.ZoneInfo.

The datetime.datetime.utcnow() function is deprecated and all occurrences of datetime.datetime.utcnow() have been replaced with the recommended datetime.now(timezone.utc) to ensure timezone-aware datetime objects in UTC.

**Pull request merged**
