### PR TITLE
Activity tracking

### PR DESCRIPTION
**Pull request by frimpongopoku**
Works with Frontend PR https://github.com/massenergize/frontend-admin/pull/706 
Ticket https://github.com/massenergize/frontend-admin/issues/664
Spec Sheet https://docs.google.com/document/d/1Y0e3tTPKbKraFPQ2VaIarE-wAxpixuHpqQD9FkvT1VM/edit?usp=sharing

### Additions 
**Footage Model** 
Represents the table that will have all records of the activities that happen on the admin portal. See `models.py` for more details and documentation.
⚠️  _Migration Alert_

**FootageConstants.py** 
Just a class that contains necessary values to help the the tracking process. Check `FootageConstants.py`

**Spy Class** 🤣
All util.. functions are grouped under this class as static functions. Here you will find all the functions that are called to record activities admins perform on the platform. Eg. Creating an action, updating, deleting, messaging etc. Check `Spy.py`

## What's Implemented?
So far the following are functional and manually tested. 
Records are created, when:

### Actions 
- [x] Admins create an action 
- [x] Admins update an action 
- [x] Admins delete an action 
- [x] Update rank 
- [x] Copy an action

### Events 
- [x] Admins create 
- [x] Admins update 
- [x] Admins delete 
- [x] Update rank 
- [x] Copy 

### Vendors 
- [x] Admins create 
- [x] Admins update 
- [x] Admins delete 
- [x] Update rank 
- [x] Copy 

### Testimonials 

- [x] Admins Update Testimonials 
- [x] Update rank 

### Team 
- [x] Admins create 
- [x] Admins update 
- [x] Admins add team members 
- [x] Remove team members 
- [x] Delete team 

### Message 
- [x] Reply normal admin messages 
- [x] Reply team messages 
- [x] Admins delete messages

### Events 
- [x] Admins (sadmins)  create 
- [x] Admins update 
- [x] Admins (sadmins) delete 

### New Route 
`/what.happend` 🤣 

This route fetches all activities that are related to whoever is signed in on the portal. 

**Super Admins** will see all activities that other super admins have been performing 
**Community Admins** will see only activities that have happened in the communities they are admins of, and that includes changes super admins have made related to their communities
The frontend implementation of this is done in this PR https://github.com/massenergize/frontend-admin/pull/706 

**Would like to know what everyone thinks 🤔**

- [x] **Next > Backend Tests**

### CODE REVIEW

**Comment by BradHN1** [comment]
Can you link this PR to the issue ticket which defines the feature being implemented?

**Comment by Davidjwkinghorn** [comment]
I've felt we've needed something like this for a while now. Logging activities can be super valuable if we ever have to do damage control after unauthorized or harmful usage of the admin portal.

**Comment by frimpongopoku** [comment]
Exactly!

**Review by Davidjwkinghorn — APPROVED** [review]
LGTM

**Comment by Davidjwkinghorn** [comment]
Tests are failing, is that something we need to address or should we not trust the tests? Is it a result of the DB changes?

**Comment by Davidjwkinghorn** [comment]
This PR seems to be causing some issues with our tests. @frimpongopoku can you look into this?

**Comment by frimpongopoku** [comment]
It is, but the ticket was  created on the admin board so I had to link it
to frontend PR. I think its 664.

**Pull request merged**
