### PR TITLE
restored and renamed custom migration file

### PR DESCRIPTION
**Pull request by Davidjwkinghorn**
####  Summary / Highlights
I restored some custom changes @BradHN1 made to the autogenerated migration file and renamed the file to reflect that.

#### Requirements (place an `x` in each `[ ]`)
* [x] I've read and understood the [Contributing Guidelines](/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've tested my changes manually.
* [ ] I've added unit tests to my PR.

##### Transparency ([Project board](https://github.com/orgs/massenergize/projects/7/views/2))
* [x] I've given my PR a meaningful title.
* [ ] I linked this PR to the relevant issue.
* [ ] I moved the linked issue from the "Sprint backlog" to "In progress" when I started this.
* [ ] I moved the linked issue to "QA Verification" now that it is ready to merge.

### CODE REVIEW

**Comment by Davidjwkinghorn** [comment]
I need to resolve some conflicts between this and the previous migration file before this can be moved forward.

**Review by BradHN1 — APPROVED** [review]
LGTM - though you'll need to resolve the conflict between the autogenerated 0119 and the new one

**Comment by Davidjwkinghorn** [comment]
> LGTM - though you'll need to resolve the conflict between the autogenerated 0119 and the new one

Yeah, just noticed that.

**Comment by Davidjwkinghorn** [comment]
Correct me if I'm wrong, but the only conflict was the dependency (which I had forgotten to change). They're not dealing with the same models/fields.

**Pull request merged**
