### PR TITLE
Open and closed events

### PR DESCRIPTION
**Pull request by frimpongopoku**
### Works with frontend portal API https://github.com/massenergize/frontend-portal/pull/1128

- [X] Event model now has "publicity" field which can take 4 values ( OPEN, OPEN_TO, CLOSE, CLOSED_TO). 
OPEN = the event can be shared anywhere, and is the default value for any new event 
OPEN_TO = Only open to a few selected people 
CLOSE = Closed to everyone 
CLOSED_TO = Open to everyone, except communities that the admin has selected 

- [X] `communities_under_publicity` will hold communities that have been selected under OPEN_TO / CLOSED_TO   
- [X] `shared_to` field is a new field that will hold all communities that an event has been shared to
- [X]  Events that have been shared to a community will be added on to the events list when the user portal loads `events.list`

### CODE REVIEW

**Comment by frimpongopoku** [comment]
Will invest the tests failures, but the PR is still up for testing.

**Review by abdullai-t — APPROVED** [review]
✅

**Comment by Davidjwkinghorn** [comment]
I generated some migrations. @frimpongopoku can you check these to make sure they look good. Let me know if anything needs adding/changing.

**Comment by Davidjwkinghorn** [comment]
I think my migrations may be missing a script or default values or something. Got this error message when creating a closed event.

Screen Shot 2022-11-08 at 4 45 02 PM

**Comment by BradHN1** [comment]
This looks like screwed up migrations, you may need to roll one back.  Let me know if you want to meet up to do this.

**Comment by Davidjwkinghorn** [comment]
> This looks like screwed up migrations, you may need to roll one back. Let me know if you want to meet up to do this.
It definitely is migration related, the migrations weren't added in this PR so I generated them myself. I think I'm missing a default or script that should resolve this.

**Comment by Davidjwkinghorn** [comment]
Tests are still failing on this. Is this WIP or is something else broken?

**Comment by frimpongopoku** [comment]
> Tests are still failing on this. Is this WIP or is something else broken?

Everything passes when I run the tests locally though?🤔

**Pull request merged**
